// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDXenbyM40ymNsvGf2Ue9kXDwyNH3tSnI',
    appId: '1:659643572325:web:fdb3990bb09032a2baa68c',
    messagingSenderId: '659643572325',
    projectId: 'multivendorapp-9a087',
    authDomain: 'multivendorapp-9a087.firebaseapp.com',
    storageBucket: 'multivendorapp-9a087.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANQzLTUlrGW3LpjrN8JJFb0Yia6VxiAsk',
    appId: '1:659643572325:android:772d244c0ddc32cfbaa68c',
    messagingSenderId: '659643572325',
    projectId: 'multivendorapp-9a087',
    storageBucket: 'multivendorapp-9a087.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrJxM-OKXrJrRcBiDsMTZvVo1Yqx2PocA',
    appId: '1:659643572325:ios:8e3f6500d462425ebaa68c',
    messagingSenderId: '659643572325',
    projectId: 'multivendorapp-9a087',
    storageBucket: 'multivendorapp-9a087.appspot.com',
    iosClientId: '659643572325-28ghsqrdl34j5slitcan0l8ic9m97h9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.mutliVendorAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrJxM-OKXrJrRcBiDsMTZvVo1Yqx2PocA',
    appId: '1:659643572325:ios:28b770b0cf1c0979baa68c',
    messagingSenderId: '659643572325',
    projectId: 'multivendorapp-9a087',
    storageBucket: 'multivendorapp-9a087.appspot.com',
    iosClientId: '659643572325-873s44mtquq7qp337dtpacalf9qf52gc.apps.googleusercontent.com',
    iosBundleId: 'com.example.mutliVendorAdmin.RunnerTests',
  );
}
